/*
 * Copyright © Jean Silva
 *
 * This file is part of the Key6 open-source project.
 *
 * Key6 is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Key6 is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see https://www.gnu.org/licenses.
 */

import com.android.build.api.dsl.CommonExtension
import com.diffplug.gradle.spotless.FormatExtension
import com.diffplug.gradle.spotless.HasBuiltinDelimiterForLicense
import com.diffplug.spotless.kotlin.KtfmtStep
import groovy.util.Node
import groovy.util.NodeList
import groovy.xml.XmlParser
import java.io.FileNotFoundException
import java.nio.file.Paths
import kotlin.io.path.isRegularFile
import org.apache.commons.text.WordUtils
import org.tomlj.Toml

plugins {
  alias(libs.plugins.android.application) apply false
  alias(libs.plugins.android.library) apply false
  alias(libs.plugins.java)
  alias(libs.plugins.spotless)
  kotlin("jvm") version "2.3.0"
}

kotlin.jvmToolchain(21)

allprojects { repositories.mavenCentral() }

buildscript {
  dependencies {
    classpath(libs.apache.commons.text)
    classpath(libs.tomlJ)
  }
}

subprojects {
  extensions.findByType<CommonExtension>()?.apply {
    compileOptions.sourceCompatibility = JavaVersion.VERSION_17
    compileOptions.targetCompatibility = JavaVersion.VERSION_17
    defaultConfig.testInstrumentationRunner =
      "androidx.test.runner.AndroidJUnitRunner"

    buildTypes.getByName("release") {
      isMinifyEnabled = true
      proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"))
    }
  }

  repositories {
    google()
    gradlePluginPortal()
  }
}

spotless {
  val editorConfigPath = Paths.get(projectDir.toURI().resolve(".editorconfig"))
  if (!editorConfigPath.isRegularFile()) {
    throw FileNotFoundException(".editorconfig")
  }
  val maxLineLength =
    Toml.parse(editorConfigPath)
      .getLong("max_line_length")
      .requireNotNull { "Missing 'max_line_length' in .editorconfig." }
      .toInt()
  val licenseHeaderFile =
    projectDir
      .toPath()
      .resolve(".idea")
      .resolve("copyright")
      .resolve("${project.name}.xml")
      .toFile()
  if (!licenseHeaderFile.isFile) {
    throw FileNotFoundException(
      "License header file generated by IntelliJ not found.",
    )
  }
  val licenseHeaderOptions =
    XmlParser()
      .parse(licenseHeaderFile)["copyright"]
      .let { it as NodeList }
      .filterIsInstance<Node>()
      .firstOrNull { it.name() == "copyright" }
      .requireNotNull { "License header file missing copyright information." }
      .children()
      .filterIsInstance<Node>()
  val licenseHeader =
    licenseHeaderOptions
      .firstOrNull { it.attribute("name") == "notice" }
      .requireNotNull { "License header not found in IntelliJ-generated file." }
      .attribute("value")
      .let { it as String }

  format("misc") {
    endWithNewline()
    target("*")
  }

  java {
    expandWildcardImports()
    googleJavaFormat("1.35.0").reflowLongStrings()
    removeUnusedImports()
    target("**\\/*.java")
  }

  java {
    cStyleBlockLicenseHeader(licenseHeader, maxLineLength)
    target("**\\/com\\/jeanbarrossilva\\/key6\\/*.java")
  }

  kotlin {
    ktfmt("0.62").googleStyle().configure {
      it.setBlockIndent(2)
      it.setContinuationIndent(2)
      it.setMaxWidth(maxLineLength)
      it.setTrailingCommaManagementStrategy(
        KtfmtStep.TrailingCommaManagementStrategy.NONE,
      )
    }
    target("**\\/*.kt", "**\\/*.kts")
    targetExclude(
      "keychain/src/main/java/com/jeanbarrossilva/key6/keychain/" +
        "CharSequence+Count.kt",
    )
  }

  kotlin {
    cStyleBlockLicenseHeader(licenseHeader, maxLineLength)
    target("**\\/com\\/jeanbarrossilva\\/key6\\/**\\/*.kt", "**\\/*.kts")
  }
}

/**
 * Alias for `requireNotNull(this, lazyMessage)`.
 *
 * @param lazyMessage Produces the message to be printed out to standard error
 *   in case this is `null`.
 */
private fun <T> T?.requireNotNull(lazyMessage: () -> String) =
  requireNotNull(this, lazyMessage)

/**
 * Includes the license header as a C-style block comment (`/* … */`) at the
 * beginning of each target file.
 *
 * ###### Implementation notes
 *
 * This function uses the [WordUtils.wrap] function from Apache Commons Text.
 * The correct wrap length is provided to it, [maxLineLength] - 3 (given that
 * each line is prefixed by " * "), but some lines may get wrapped earlier than
 * expected. This appears to be a bug in the implementation of that function.
 *
 * @param licenseHeader Header of the license of files being targeted.
 * @param maxLineLength Maximum amount of characters a line should contain.
 *   Normally, this would be the same as that defined by default by the format
 *   or that specified manually for target files.
 */
private fun HasBuiltinDelimiterForLicense.cStyleBlockLicenseHeader(
  licenseHeader: String,
  maxLineLength: Int,
): FormatExtension.LicenseHeaderConfig =
  licenseHeader(
    "/*\n" +
      WordUtils.wrap(
          licenseHeader,
          // wrapLength =
          maxLineLength - 3,
          // newLineStr =
          "\n",
          // wrapLongWords =
          false,
          // wrapOn =
          " |\n",
        )
        .lines()
        .joinToString(separator = "\n * ", prefix = " * ") +
      "\n */\n\n",
  )
